workflows:
    android-app:
        name: fast-mixer
        scripts:
            - cd android && chmod +x gradlew && ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/**/*.apk
        publishing:
            email:
               recipients:
                   - msawon94@gmail.com
            github_releases:
                prerelease: true
                artifact_patterns:
                   - '*.apk'
